version: '2'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - "8095:80"
  php:
    build:
        context: .
        dockerfile: phpImage
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7
    ports:
      - "3321:3306"
    volumes:
      - ./.mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 42
      MYSQL_USER: scrabble
      MYSQL_PASSWORD: localpass
      MYSQL_DATABASE: scrabble
